### ISSUE TITLE
ElasticSearch index is not being created automatically on the first run

### ISSUE THREAD

**Issue by KrishnaPG** [CodeChain-io/codechain-explorer#56]
Failed with error that index 'block' did not exist. 
````
[0] [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="block" & index_uuid="_na_" & index="block" } :: {"path":"/block/_doc/_search","query":{},"body":"{\"sort\":[{\"number\":{\"order\":\"desc\"}}],\"size\":1,\"query\":{\"bool\":{\"must\":{\"term\":{\"isRetracted\":false}}}}}","statusCode":404,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"block\",\"index_uuid\":\"_na_\",\"index\":\"block\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"block\",\"index_uuid\":\"_na_\",\"index\":\"block\"},\"status\":404}"}
[0]     at respond (C:\Users\gk\Desktop\codechain-explorer\node_modules\elasticsearch\src\lib\transport.js:308:15)
[0]     at checkRespForFailure (C:\Users\gk\Desktop\codechain-explorer\node_modules\elasticsearch\src\lib\transport.js:267:7)
[0]     at HttpConnector.<anonymous> (C:\Users\gk\Desktop\codechain-explorer\node_modules\elasticsearch\src\lib\connectors\http.js:165:7)
[0]     at IncomingMessage.wrapper (C:\Users\gk\Desktop\codechain-explorer\node_modules\lodash\lodash.js:4949:19)
[0]     at emitNone (events.js:110:20)
[0]     at IncomingMessage.emit (events.js:207:7)
[0]     at endReadableNT (_stream_readable.js:1056:12)
[0]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[0]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
````
And when the index was manually created in the ES backend, failed with errors about absence of _mapping_, and then another index named 'transaction' so on...

These should be auto created on start, or please provider a script that can be run to setup the whole ES index and mappings.

**Comment by xpdlf1004** [comment]
CodeChain Explorer has a dependency on the [CodeChain-indexer](https://github.com/CodeChain-io/codechain-indexer). You need to run the Indexer first.

The CodeChain indexer creates the mapping for the Elasticsearch automatically before it running. And It'll index the CodeChain data to the ES.

Please,  try to follow the instructions in the README of the indexer project. And If you have a problem, create an issue again.

FYI, we are using ElasticSearch v6.2.4. Thank you.
